### ISSUE TITLE
Use a faster Gaussian blur algorithm

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#125]
The current one is pretty slow and single-threaded. 

- [ ] Faster/parallel IIR blur
- [x] #83

**Comment by jrmuizel** [comment]
Maybe https://github.com/fschutt/fastblur?

**Comment by RazrFalcon** [comment]
Yes, I saw this one, but it's unfinished and RGB only. I need RGBA. And preferably with LinearRGB support.

**Comment by Shnatsel** [comment]
Could you provide a little more details to help people get started? Like where the current blur code is. And what are the special considerations for supporting ARGB and LinearRGB.

It would be a fun exercise for an external contributor if the problem was more clearly defined.

**Comment by RazrFalcon** [comment]
The code is [here](https://github.com/RazrFalcon/resvg/blob/master/src/backend_utils/filter.rs#L371..L582) and it should be faster. That's it =)

LinearRGB doesn't really needed.

**Comment by Shnatsel** [comment]
I really like the algorithm used in https://github.com/fschutt/fastblur because it's not only linear time, it's also embarrassingly parallel.

There were some clear inefficiencies in the implementation, like the use of indexing instead of iterators and needless cloning. I've killed off the cloning and started rewriting it with iterators instead of indexing. 

So far I've rewritten the horizontal pass (almost) successfully - it works, but the effective blur size is larger than before and I'm not entirely sure why. Performance is improved by 15%, and I'd expect that to grow to 20% if/when the vertical pass is also converted to iterators.

The horizontal pass is also trivially `rayon`able, but the vertical pass is less so. Although I may be getting ahead of myself here.

**Comment by RazrFalcon** [comment]
Yes, this one requires a lot of time.

**Comment by Shnatsel** [comment]
I've optimized https://github.com/fschutt/fastblur and got the execution time down from 10,7ms to 3,6ms for their sample image. This is a 3x speedup. The numbers in their README are no longer accurate.

[I've also experimented with Rayon](https://github.com/Shnatsel/fastblur/blob/rayon/src/blur.rs#L56), but only got the horizontal pass to work in parallel - without a bespoke `unsafe`, that is. To parallelize the entire thing I'd need some kind of abstraction that lets me iterate over columns in an image, or over strides in a buffer with different offsets, in parallel.

Sadly that implementation still cannot handle blur sizes larger than image sizes (https://github.com/fschutt/fastblur/issues/4).

**Comment by Shnatsel** [comment]
Okay, I made https://github.com/fschutt/fastblur now handle large blur radii as well. This regressed performance from 3.6 to to 3.8ms, which should be tolerable. I've also killed off the last vestiges of quadratic complexity.

That implementation still panics in debug mode when given an enormous radius [due to integer overflow](https://github.com/fschutt/fastblur/issues/7), but otherwise should be serviceable.

Still no RGBA, but judging by the current blur implementation in resvg it shouldn't be hard to add.

**Comment by RazrFalcon** [comment]
Nice. resvg also requires a separate radii for X and Y.

**Comment by Shnatsel** [comment]
Since the vertical and horizontal passes in that implementation are separate, that should be pretty easy to achieve, but it is not exposed through the current API.

**Comment by Shnatsel** [comment]
Ah, what the heck. [Now it does.](https://github.com/fschutt/fastblur/pull/8)

**Comment by RazrFalcon** [comment]
Nice! I will try it out tomorrow.

**Comment by RazrFalcon** [comment]
@Shnatsel The "tomorrow" is now :smile: 

1. It's a box blur, afaiu, so I still have to use the current one for small objects, because it produces a better results. According to the SVG spec I can fallback to box blur when sigma is > 2.
1. `Vec<[u8; 3]>` is a very strange input. I will loose all the performance just on converting RGBA to it and back.
1. I need an alpha support.

**Comment by jrmuizel** [comment]
FWIW, Firefox uses a box blur for all sigma.

**Comment by Shnatsel** [comment]
Yes, it's a box blur, so you do need to fall back to current implementation for small sigmas. However, at that radii the performance of the "honest" blur should be better anyway.

I didn't change the input format for that blur implementation, I just assumed you'll copy-paste the implementation it and make it use whatever format(s) you need.

Alpha support is indeed missing.

**Comment by RazrFalcon** [comment]
I didn't thought about copy-pasting...

**Comment by RazrFalcon** [comment]
@Shnatsel Finally found a time to test it out. 

It mostly works, except alpha, which is processed exactly as other channels. Here is a comparison:

![e-feGaussianBlur-001](https://user-images.githubusercontent.com/725494/63187388-6d559300-c067-11e9-8b48-f44a9ded80c3.png)

cairo uses IIR. Qt uses fastblur. Chrome for a reference.

You can see a gray aureole around a rect. Any ideas?

PS: man it's fast...

**Comment by RazrFalcon** [comment]
It's also a bit wider:

![1565979036](https://user-images.githubusercontent.com/725494/63188666-9cb9cf00-c06a-11e9-98e7-151554883cb2.png)

(fastblur on the top, firefox on the bottom)

**Comment by RazrFalcon** [comment]
The code can be found [here](https://github.com/RazrFalcon/resvg/blob/box-blur/src/filter.rs#L608).

**Comment by RazrFalcon** [comment]
An incorrect alpha processing is clearly visible with a yellow color.

![e-filter-047](https://user-images.githubusercontent.com/725494/63189965-dfc97180-c06d-11e9-8f15-70ec175d7e98.png)

**Comment by jrmuizel** [comment]
It looks like iir blur is premultiplying by alpha and box blur is not

**Comment by mstange** [comment]
This looks like either blurring happened on unpremultiplied alpha, or it happened on premultiplied alpha and the result was interpreted as unpremultiplied alpha.
Blurring premultiplied images is very nice because you can just blur all channels independently: Color contributions from less opaque pixels are automatically weighted less than color contributions from more opaque pixels. If you have unpremultiplied alpha images, you need to look at both the color channel and the alpha channel when you want to compute the blurred color channel and it's just messy to deal with.

**Comment by RazrFalcon** [comment]
@jrmuizel Yes, I should try the same algorithm for alpha that IIR uses.

**Comment by RazrFalcon** [comment]
@mstange Indeed, disabling an unpremultiplied alpha solved the issue (mostly). The problem is that SVG filters work with unpremultiplied images. And Qt and Skia support non-premultiplied images, and cairo and raqote - don't. So I have to implement a custom alpha handling anyway because of this. 
Thanks for a hint.

**Comment by RazrFalcon** [comment]
@mstange Thanks again. I didn't know that you can simply use premultiplied alpha images for a blur. This greatly simplifies the code. It also makes cairo and raqote backends a bit faster, since I don't need to do an alpha multiplications 4 times (since they are already premultiplied). 

As for the box blur/fastblur itself, it blurs vertically a bit more than horizontally.

![e-feGaussianBlur-001](https://user-images.githubusercontent.com/725494/63194507-e6111b00-c078-11e9-8f57-979fd28eaf64.png)

(left - resvg/fastblur, right - chrome)

**Comment by RazrFalcon** [comment]
To fix the issue about we should blur vertically first. No sure why.

**Comment by RazrFalcon** [comment]
Done. Thanks again to @Shnatsel for helping with it.
