### ISSUE TITLE
Unsupported SVGs analysis

### ISSUE THREAD

**Issue by therealbnut** [RazrFalcon/resvg#138]
Hey,

I'm looking into libraries to render SVGs. The company I work for has a lot of SVGs, millions of users using them, and thousands of artists contributing them. I thought you might be interested part of my evaluation of your library.

I've done my analysis on our 10k most popular SVGs, and roughly 35 million most recent uses of those (to get popularity/frequency of each). I've evaluated what percentage of those SVGs usages would fail to render with your library, and why, basing this on your [unsupported](https://github.com/RazrFalcon/resvg/blob/master/docs/unsupported.md) page.

By far the most frequent source of failure was `enable-background`, which I filtered out, as I didn't think it would affect rendering. After filtering that out I was left with 99.90% of our SVGs that _could_ be rendered. Nice work!

These are the elements and attributes combinations that contributed to those that didn't work:

|attributes|elements|percent of failures|
|-|-|-|
|'in' ||33.81%|
|'line-height', 'word-spacing' ||21.61%|
|| 'feColorMatrix' |19.28%|
|'in' | 'feColorMatrix' |15.58%|
|'in' | 'feMorphology', 'feColorMatrix', 'feDiffuseLighting', 'feDistantLight', 'feSpecularLighting' |4.59%|
|'in' | 'feSpecularLighting', 'fePointLight' |4.12%|
|'line-height', 'word-spacing' | 'textPath' |2.00%|

I hope this is useful for you, and that it will help when making decisions on any future support work.

Nice work so far with your library!

**Comment by RazrFalcon** [comment]
>enable-background

It's pretty hard to implement. Also, it's not supported [even by browsers](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#a-enable-background). Also, it was deprecated in SVG 2.0, so...

>line-height

It's not part of the SVG 1.1 Full. So it's out of scope.

>feColorMatrix

Hopefully, will be in the next release. Other filters are more time consuming.

>word-spacing, textPath

Will be fixed by a new text layout, which almost complete. `word-spacing` already works, but `textPath` will take some time. Hopefully, will be in the next release.

I can't guarantee, but I hope that at least `feColorMatrix` and `textPath` will be available in next few months.

**Comment by therealbnut** [comment]
Nice, thanks for letting me know the progress on those, that’s good to hear!

I wanted to clarify that this Issue isn’t a feature request, it was the best way I could find to share my data. I hope you find it useful :)

You’re doing great work!

**Comment by RazrFalcon** [comment]
The 0.8 version supports `feColorMatrix`, `textPath` and `word-spacing`. Advanced filters will be implemented later.

**Comment by therealbnut** [comment]
Nice, that should decrease unsupported SVGs by 20% or so 🎉
