### ISSUE TITLE
Evaluate flate2

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#143]
Looks like `flate2` is more safe than `libflate`.

**Comment by Shnatsel** [comment]
I'm now working my way through libflate, reporting sometimes and fixing the issues I discover:
https://github.com/sile/libflate/issues/29
https://github.com/sile/libflate/issues/31
https://github.com/sile/libflate/issues/33

I couldn't get any bugs out of miniz_oxide (the Rust backend for flate2) with a fuzzer, including when fuzzing with [libdiffuzz](https://github.com/Shnatsel/libdiffuzz). I have to admit that reasoning about the unsafety in miniz_oxide is beyond my abilities, but it doesn't look very reassuring. Issues like https://github.com/Frommi/miniz_oxide/issues/14 also don't instill confidence.

I can vouch for the safety of https://github.com/image-rs/inflate because I've purged all but one unsafe blocks in it, and then found and fixed the bug in the remaining unsafe block together with the maintainer. But last time I checked it was even slower than libflate.

**Comment by Shnatsel** [comment]
I'm done cleansing `libflate` of unsafe blocks. It only has one, which I've verified to be sound. Another one has been punted into a separate crate, where the implementation is heavily based on a stdlib function. So I can vouch for the safety of `libflate` as well, starting with version 0.1.25.

Also, I've since discovered a [heap buffer overflow](https://github.com/Frommi/miniz_oxide/pull/47) in miniz_oxide and likely also miniz, and would advise against using them if safety is a concern.

**Comment by RazrFalcon** [comment]
Nice! Than I will force the minimum `libflate` version.

**Comment by Shnatsel** [comment]
I believe this issue should be revisited. The Rust backend for flate2 called [miniz_oxide](https://github.com/Frommi/miniz_oxide/tree/master/miniz_oxide) is now 100% safe and [forbids unsafe code](https://github.com/Frommi/miniz_oxide/pull/56). It is also 2.5x faster on decompression than libflate.

There is still [some unsafety in flate2](https://github.com/rust-secure-code/safety-dance/issues/2#issuecomment-521293940), so I'd suggest using miniz_oxide directly. This would improve performance, provide compiler-guaranteed safety and reduce the number of dependencies.

**Comment by RazrFalcon** [comment]
Thanks. I will try it out.

**Comment by RazrFalcon** [comment]
I've switched to `flate2`, but not to `miniz_oxide` directly. Since I need gzip support.
