### ISSUE TITLE
feComposite incorrectly clamps arithmetic input parameters

### ISSUE THREAD

**Issue by ds84182** [RazrFalcon/resvg#170]
I don't see where the clamp is specified on https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite, and it produces incorrect results with SVGs that use negative constants to subtract layers from each other.

Would you accept a PR to remove the clamp and to add a test case?

**Comment by RazrFalcon** [comment]
Can you clarify what value exactly is getting clamped? And can you provide a test example?

**Comment by RazrFalcon** [comment]
It's actually an undefined behavior, afaik. See https://github.com/w3c/csswg-drafts/issues/3831 The SVG spec doesn't specify the range of k1-4 values.

Here is my results:

![i170-1](https://user-images.githubusercontent.com/725494/63747859-c4056d00-c8b0-11e9-93e2-df8a9580f653.png)

Looks like browsers are ignoring the negative values, but keep positive >1. I already have a similar test case [e-feComposite-015.svg](https://raw.githubusercontent.com/RazrFalcon/resvg-test-suite/master/svg/e-feComposite-015.svg) and all apps produce the same results.

Since I'm not sure how the correct result should look like we can simply mimic the browsers for now (e.g. by removing the 1.0 cap, but ignoring `feComposite` with negative coefficients).

**Comment by RazrFalcon** [comment]
Agree. I was looking into exactly the same sources while implementing `feComposite` in the `resvg`. 
The problem is that there are no right answer. I can implement the `arithmetic` operator in a way I interpreted the spec or just follow the others.

I think that in this specific case we should allow coefficients above 1.0, to match browsers, and discuss negative one [here](https://github.com/w3c/csswg-drafts/issues/3831) or [here](https://github.com/w3c/fxtf-drafts/issues). We should get a specific answer from the SVG authors themselves. So we can reference it later.

PS: and this is not something unique. resvg test suite filled with UB. There are just a lot of stuff that is undefined in the spec. Also note that resvg targets SVG 1.1, while browsers implement whatever they want.

**Comment by RazrFalcon** [comment]
I've allowed coefficients larger than 1.0, but negative one still will be clamped.
