### ISSUE TITLE
Remove all backends except raqote

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/resvg#195]
Originally, when `resvg` was started (2.5 years ago) there was no [raqote](https://github.com/jrmuizel/raqote). So the only solution was to use an existing 2D libraries like cairo and Qt.

The initial requirements for a 2D library were:

- Shapes rendering (filling, stroking, gradients, patters).
- Layers compositing.
- Text rendering (the most complex one).
- JPEG/PNG handling.

But that was a long time ago. Right now, `resvg` requires only the first two points. Text rendering, JPEG/PNG handling, and filters are done in a backned-independent manner already. So the only reason to have multiple backends is to render very simple SVG images (no opacity, clipping, masking, filters, images) on an existing canvas.

So the idea is to remove all backends except `raqote`, while C API will be changed to return just a `Vec<u8>` as a resulting image (not PNG encoded).

This will simplify things quite a bit. The only downside is that `raqote` is a bit slow and unstable. But this can (and will) be fixed.

@JaFenix, @therealbnut if you are still using `resvg`, what are your thoughts about this change? Is it absolutely necessary to have a Skia based backend for you?

**Comment by Shnatsel** [comment]
For context, this does not impact out-of-tree "backends" such as Lyon and Pathfinder - they use `usvg` crate only.

**Comment by RazrFalcon** [comment]
Yes, `usvg` isn't going anywhere. `resvg` will still be split into two modules.

**Comment by JaFenix** [comment]
For rendering purposes, there isn't anything specific about Skia that would be necessary for me.  Provided that Raqote executes safely and efficiently inside of an OpenGL (hardware accelerated), Skia-based application, then it should not be necessary to have a Skia specific backend.  It would be sufficient for the C API to return a pointer to a rendered bitmap.  

Performance and memory consumption are the only concerns.  The performance will ideally have to be as good as Skia's software renderer, or at least as good as a web browser (some of which use Skia), because our application competes with the browsers in terms of rendering performance.  I imagine there will be some additional memory overhead with loading the Raqote library into the application's process in addition to Skia.  Currently, we only load Skia, so this affords us a nice optimization.

One minor thing that's specific to the Skia backend is the render_rect_to_canvas() function which I've added to the backend_skia/mod.rs file in our m58 branch (https://github.com/JaFenix/resvg/blob/611fb21f4912f89bce0a4aaf60b0be6687efb342/src/backend_skia/mod.rs#L119).  This function allows the calling application to specify a region of the SVG to render, instead of the whole thing.  But this does not require Skia, so if it were available in the proposed C API or could be added in a fork, then  we'd be OK without the Skia backend code.

So the proposal sounds good once the benchmarks are there, and we would have used resvg in the beginning like it's being proposed now.  However, I do think resvg has a good architectural model by which different backends can be constructed and selected by application developers.  This (in theory) makes it possible to use the optimized aspects of one backend over another.  It's a nice selling point and it might mean giving up these advantages if the backend model were eliminated.

**Comment by therealbnut** [comment]
Thanks for reaching out @RazrFalcon, I'll have a more in-depth think about it, but here's my initial thoughts:

We pretty much do this:
> the only reason to have multiple backends is to render very simple SVG images (no opacity, clipping, masking, filters, images) on an existing canvas.

 * We also want to have a similar `render_rect_to_canvas` capability to what @JaFenix mentioned.
 * We prefer to be able to output to vector (Skia's PDF backend), with simple SVGs, something that's not really supported at the moment, but just happens to work most of the time. I don't think raqote supports vector output.

We'd lose a lot of our value from resvg if we couldn't do those things. I personally feel it'd be a shame to lose the flexibility, but I understand the pragmatism.

Maybe you could start by reducing support to raqote _and_ Skia for a transitionary period, it might reduce the complexity and have more overlap for a common backend interface?

**Comment by RazrFalcon** [comment]
@JaFenix Thanks for a detailed feedback.

According to my ["benchmarks"](https://github.com/RazrFalcon/resvg#performance), `raqote` isn't that slow, but still considerably slower than Skia. I hope that this can be fixed soon. I do not plan to remove other backends right now.

Memory overhead should be the same. There are no changes there. As for the library size overhead, according to the `cargo-bloat`, `raqote` adds like 100KiB, so it's basically nothing. Especially since `usvg` itself is like 500KiB and HarfBuzz adds like 800KiB.

>or at least as good as a web browser

raqote is used in Servo. If you can call it a browser :smile: But yes, performance is the main concern.

>render_rect_to_canvas

How exactly does it work? Is it simply a clip-path? 

>It's a nice selling point and it might mean giving up these advantages if the backend model were eliminated.

I agree. And support for custom backends isn't going anywhere. The problem is that current backends lost their purpose.

**Comment by RazrFalcon** [comment]
@therealbnut Yes, I thought about a PDF export. But as I already said in the related issue, it's broken by design. Yes, it sort of works, but we need a dedicated PDF backend anyway.

>Maybe you could start by reducing support to raqote and Skia for a transitionary period

Yes. This is a good idea. I'm thinking about removing Skia from the main library (e.g `resvg`) and reimplementing it as a separate library/repo. With its own C API, etc. The only problem is that filters should be extracted into a separate crate. 

The problem with multiple backends is that it confuses some people, build instructions become notorious, etc. So I want to make the main repo/lib more focused and simple, but also have separate implementations.

**Comment by JaFenix** [comment]
@RazrFalcon

> How exactly does it work? Is it simply a clip-path?

render_rect_to_canvas works a like a "zoom in" function.  The src parameter is a rectangle within the bounds of the screen size of the SVG (i.e. tree.0.svg_node().size.to_screen_size()).  This src rectangle is scaled into the bounds of a destination rectangle (img_size) when rendered.  For example, if the SVG contained a 500x100 map of the world, render_rect_to_canvas could select an area (src rect) around one country and render that to a 1000x1000 image (img_size).  This "zoom in" effect is accomplished by applying the viewbox transform to the screen size of the SVG rather than the img_size, and translating/scaling the src rectangle from the SVG screen size into the destination img_size.

**Comment by RazrFalcon** [comment]
I'm not sure if this can be considered as an optimizations, since resvg always renders the whole canvas.

**Comment by JaFenix** [comment]
@RazrFalcon
render_rect_to_canvas is not intended to be a performance optimization, but rather a way to clip & scale part of the SVG without pixellation.  Our users have an editor that allows them to add images to their "page" at various sizes and clip regions.   They don't really distinguish between SVG, PNG, JPG, etc, except they do expect that SVGs will not pixellate when clipped & stretched.  So render_rect_to_canvas is designed to take a source clip region and destination size and render the SVG to those specifications.

To do this, I found it necessary to push the sequence of transformation matrices onto the Skia canvas prior to rendering.  However, I did this inside of resvg because the translate/scale (clipping) transformation has to be applied before the viewbox transform, which is calculated and applied _inside_ of resvg.   In other words, I could not set the canvas matrix before passing it in because some of the information (viewbox dimensions) is available and applied inside resvg.  Likewise, apply clipping & stretching after rendering would result in pixellating the image.

**Comment by RazrFalcon** [comment]
I see. I think it might be a good addition to the API.

**Comment by olilarkin** [comment]
makes sense to me. looking forward to trying the raqote with the capi when it can output raw data

**Comment by RazrFalcon** [comment]
Looks like raqote is way too far from completion. Closing this for now.
