### ISSUE TITLE
How to fix fonts?

### ISSUE THREAD

**Issue by fishrockz** [RazrFalcon/resvg#200]
How do i fix this?

I am running on fedora and was wondering if I'm just missing a font on the system but I packages that clam to provide a Times new roman font.

I have added the text feature to the Cargo.toml depending on usvg

2020-01-11 18:47:37,622 WARN  [usvg::convert::text::convert] No match for 'Times New Roman' font-family.

**Comment by RazrFalcon** [comment]
A required font should be in one of those paths:

- /usr/share/fonts/
- /usr/local/share/fonts/
- ~/.local/share/fonts

**Comment by RazrFalcon** [comment]
You can also try adding a `println!("{}", item)` before [this](https://github.com/RazrFalcon/resvg/blob/0c1219667a27b39792c59fd24c1f628808f57d01/usvg/src/fontdb.rs#L553) line for debug purposes.

**Comment by fishrockz** [comment]
Turns out fedora dosn't have "Times New Roman" by default.
Apparently it not libra enough.
Would it be a good idea to make sure the default is actually installed? or if there is no match to fall back to something installed?
Any way easy to fix, if anyone else finds this, the fedora package that makes this work is:  `wine-times-new-roman-fonts-system`
Many thanks @RazrFalcon for all the help

**Comment by RazrFalcon** [comment]
You can change fallback font using `--font-family` or via `usvg::Options::font_family`.

**Comment by fishrockz** [comment]
Can i do that from a separate lib?
I still think falling back to no font at all is suboptimal, but that's just my opinion

**Comment by RazrFalcon** [comment]
Yes, you can. 

This is a default behavior for SVG.

**Comment by daviddeutsch** [comment]
I'm also having trouble with loading fonts which still prevents me from using resvg instead of inkscape :disappointed:

Ubuntu stores my fonts in ~/.fonts, but even when I copy them over to ~/.local/share/fonts, it seems like resvg does not look into my ~/.config/fontconfig/fonts.conf.

My problem is that I often get source files with broken font declarations, so I'm using fonts.conf to create aliases for those.

I'd be happy to use a resvg-native solution to this issue if looking up fonts.conf is a problem. I guess the other solution would be to always modify incoming source files with specific matchings but I have not yet explored how feasible that would be and I guess other users might expect a tool like resvg to work with fonts.conf like this.
