### ISSUE TITLE
Support providing a separate fontdb

### ISSUE THREAD

**Issue by hjmallon** [RazrFalcon/resvg#202]
I would like to provide my own set of fonts with my application (as binary objects) and not reply on any system fonts at all. Is there a way to skip all system font resolution and to provide a font manually?

**Comment by RazrFalcon** [comment]
No. Right now you can use only the system fonts, but I plan to implement custom fonts in the future.

**Comment by hjmallon** [comment]
I'd be happy to work on providing a custom fontdb. Did you have any thoughts on an API?

**Comment by RazrFalcon** [comment]
Well, it will be a pretty substantial change, so I think it would be better if I write it myself. I also thought about moving `fontdb` into a separate create, so this is a good reason to do so. Not sure when I will have time to do this.

**Comment by dabreegster** [comment]
I'm experimenting with using usvg + lyon to render text to triangles, and I wound up with need for this. https://github.com/dabreegster/resvg/commit/101872af36ec2c0fd040fdecd01d3cf34e885a67 is a quick change to load fonts from a specified directory. It'd be pretty simple to plumb through bundled binary font data through usvg::Options as well. If you want to design this much more carefully, I completely understand; I just wanted to try this out quickly.

**Comment by RazrFalcon** [comment]
@dabreegster, yes, it's quite easy to hack right now. But I want a proper solution. 

If I would not have time to implement it until the next release, I will add an option first.

**Comment by zimond** [comment]
So could we at least have an option for now? This is really what I need most :-)

**Comment by RazrFalcon** [comment]
It will be done when it will be done.

**Comment by RazrFalcon** [comment]
@dabreegster Done. It was a very complicated change that affected almost everything, but you can use any font files you want. 

@ferdnyc Hi! Looks like you was also interested in this feature. It's not available through `ReSvg.h` yet.

**Comment by ferdnyc** [comment]
@RazrFalcon Thanks for the ping!

TBH I don't know whether we'd really end up making use of this, my strong preference is to stick with what's available on the user's system rather than mucking around with forcibly loading fonts from our application directory. 

(In part because experience tells me that if we do that, we're likely to end up doing it unconditionally. Which means we'd then be overriding the majority of our users' perfectly-working setups, just to paper over the broken ones causing trouble for a much smaller but vocal minority.)

That link from our issue was me expressing surprise, upon discovering that this request had effectively **originated** with us in #159. But that was a lifetime ago, on a library integration timescale.

I can't say for sure we _won't_ make use of this support at some point, thought. It sounds like a handy option to have, just in case.

**Comment by RazrFalcon** [comment]
@ferdnyc No problem. I just wanted to let you know about this feature.

**Comment by dabreegster** [comment]
@RazrFalcon Thanks for this massive change! I switched over in https://github.com/dabreegster/abstreet/commit/4454ff73d967c2ddca0506b478365ffaac680b68 and almost everything looks fine. Is there a way to keep exposing `usvg::Font` so I could call `height()`? I added `#[cfg(feature = "text")] pub use fontdb_ext::{DatabaseExt, Font};` to get the prototype working, but I don't know if you intended to expose this as a public API.

Later down the line (not a priority anytime soon), I'll send a PR to make the `memmap2` dependency in fontdb optional, so that the crate will be WASM-friendly. WASM users will just use `Source::Binary`.

**Comment by dabreegster** [comment]
Also, IIUC, `load_font` in `DatabaseExt` is called for every new call to `usvg`, which internally does parsing (`ttf_parser::Font::from_data`). For my use case even in debug mode; I've never noticed any performance hit from this. But is there a reason to not store the `usvg::Font` in the DB?

**Comment by RazrFalcon** [comment]
The intended way is to use:

https://github.com/RazrFalcon/fontdb/blob/818bfe3de8be75dde947aeebef82ac6b0c7be1e4/src/lib.rs#L332..L366

**Comment by RazrFalcon** [comment]
>For my use case even in debug mode; I've never noticed any performance hit from this.

This hasn't changed. `usvg` was always like this. Anyway, it should be instant.

>But is there a reason to not store the usvg::Font in the DB?

DB stores font faces info. `usvg::Font` stores usvg-specific info. I can't store it the DB.

**Comment by dabreegster** [comment]
> The intended way is to use:

Ah thanks, I didn't see that line height is so simple. [Updated](https://github.com/dabreegster/abstreet/commit/882c0854456710bfb31664f7ca2593ae9ad149c3). Thank you!

> This hasn't changed. usvg was always like this. Anyway, it should be instant.

I guess I imagined TTF parsing being expensive enough to cache, but your crate is solid evidence otherwise. :)


I'm seeing an interesting issue where despite `font-family="Roboto"`, Overpass is getting chosen when the Unicode ▼ is in the `tspan`. I'm looking into it; I think there's a bug on my end. After I sort that out, I'll merge the cutover to fontdb into abstreet's master. Thanks again for all of your help!

**Comment by RazrFalcon** [comment]
If a font doesn't have a required glyph, usvg will fallback to a pseudo-random one.
