### ISSUE TITLE
The implementation of ImageExt::into_srgb() differs between backends

### ISSUE THREAD

**Issue by jrmuizel** [RazrFalcon/resvg#209]
Qt does:
```rust
    fn into_srgb(&mut self) {
        svgfilters::from_linear_rgb(self.data_mut().as_bgra_mut());
    }
```
while raqote does:
```rust
    fn into_srgb(&mut self) {
        let data =  self.get_data_u8_mut();
        svgfilters::demultiply_alpha(data.as_bgra_mut());
        svgfilters::from_linear_rgb(data.as_bgra_mut());
        svgfilters::multiply_alpha(data.as_bgra_mut());
    }
```
The Qt version is much faster. Why can it avoid doing the demultiply and multiply?

**Comment by RazrFalcon** [comment]
Because QImage can store premultiplied and unmultiplied values. In filters I'm using unmultiplied one.

https://github.com/RazrFalcon/resvg/blob/a5f575618b39e3e23bee5657bf02541b270ce450/src/backend_qt/filter.rs#L93

vs

https://github.com/RazrFalcon/resvg/blob/a5f575618b39e3e23bee5657bf02541b270ce450/src/backend_qt/mod.rs#L16
