### ISSUE TITLE
trimms shadow

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#253]
#### What happened?
|lib|pic|
|-|-|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/2/26/Golden_Mask_Award.svg)
|ink|![Golden Mask Award](https://user-images.githubusercontent.com/15687581/75591264-9677c700-5a7f-11ea-9a6c-4b9bdaf26c7c.png)
|resvg|![Golden Mask Award_resvg](https://user-images.githubusercontent.com/15687581/75591273-9b3c7b00-5a7f-11ea-839c-634eb4ce8d65.png)
|rsvg|![Golden Mask Award_rsvg](https://user-images.githubusercontent.com/15687581/75591279-9e376b80-5a7f-11ea-9e92-667b5a54f816.png)

#### What should have happened?
 - the smal "head" on the "forehead" has a trimmed shaddow at the bottom

#### Copyright

source

author

license 

#### Version and Operating System:

- Inkscape Version: 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment]
I must say, that is one striking image =)

As for the bug, resvg produces exactly the same image as Chrome, therefore it is correct.

PS: Just a note, but Inkscape and rsvg (especially the old one you're using) **must not** be used as a reference implementation, since in 95% of the cases they will be wrong. Believe me, I'm testing them for the past three years. Just looks at the spec conformance charts in the resvg's readme.
