### ISSUE TITLE
Feature request: stylesheet injection

### ISSUE THREAD

**Issue by pontaoski** [RazrFalcon/resvg#277]
Title is self-explanatory: the ability to add a stylesheet when rendering an SVG without needing to modify the XML input.

**Comment by RazrFalcon** [comment]
Yes, I do have plans on such feature, but I still not sure in what order an external css should be applied. Before or after the embedded one.

**Comment by JoKalliauer** [comment]
@RazrFalcon FYI: @federicomenaquintero declared at librsvg:

> The external CSS is loaded as for the [User origin](https://developer.mozilla.org/en-US/docs/Glossary/Style_origin); the styles declared in the SVG document have the Author origin.  The cascading rules make use of the origin and specificity of a selector to determine what takes precedence.

That makes sense for me, since the svg-specific css is generally imho more specific than the external one.

Example: Wikimedia renders the math-latex-equations somehow from svg2png using librsvg (but wihtout any css). If something is specified in the equation something should overwrite (i.e. higher priority) general one from the surrounding text (e.g. current text-color).

**Comment by edhebi** [comment]
Hi, are there still plans for that feature and/or are there specific blocking elements or other priorities ? I would be willing to contribute time to implement it, but I'm wondering if this is at the implementation or design stage.

Sincerely

**Comment by RazrFalcon** [comment]
The main blocking issue is that I have no time. 
The only hard part here is to figure out the order of CSS. Should the injected CSS override the SVG/embedded CSS properties or not. Which means testing. Which takes time.

If you want to try it, you should start here: https://github.com/RazrFalcon/resvg/blob/6be2f2d396e539ddfcf022dc67f304d307c1211a/crates/usvg-parser/src/svgtree/parse.rs#L505
