### ISSUE TITLE
Allow rendering on an existing canvas

### ISSUE THREAD

**Issue by chrsan** [RazrFalcon/resvg#309]
Hi!

Thanks for a great lib.

We’re using `0.9.0` from a FFmpeg filter using the Cairo backend. We must be able to create a surface (`MakeRasterDirect` in Skia) from a pixel buffer and call render on the canvas from that surface.

How do you feel about adding support for this? I would be happy to submit a PR.

**Comment by RazrFalcon** [comment]
Right now, `resvg` produces an RGBA buffer. You can do whatever you want with it. So I'm not sure what is the issue.

**Comment by chrsan** [comment]
The buffer we pass in 0.9.0 is the buffer for the video frame and use that to overlay SVG. We could get the buffer RGBA buffer for the SVG and blend that with the video frame buffer, but the nice part about 0.9.0 is that we don’t have to do that extra allocation.

**Comment by RazrFalcon** [comment]
Yes, I understand that. But SVG rendering is allocation heavy by it's nature. If you are rendering just a simple contour, yes, it can be faster. But in most cases, resvg will allocate multiple layers anyway. Which makes the approach with a native canvas useless. 

Also, there were too many people who misused it.

So, the is no clear solution for me. I do plan to add a new struct that wraps a Skia canvas, to reduce the amount of allocations, but it also add a lot of complexity, since Skia, as all other libraries, uses premultiplied colors by default.

**Comment by RazrFalcon** [comment]
Should be fine now. The `resvg_render` method accepts a premultiplied RGBA8888 buffer now. So the only thing you should do is to convert you bitmap to this format, render SVG, and convert it back.
