### ISSUE TITLE
Multiple backends support

### ISSUE THREAD

**Issue by andreygursky** [RazrFalcon/resvg#319]
I've noticed "All backends except Skia were removed" https://github.com/RazrFalcon/resvg/commit/8262079a7814a450891520133f74841ef74ebabb removing all backends support except of one without any justification.

From https://github.com/RazrFalcon/resvg/blob/v0.11.0/README.md
> So it's very easy to implement a new rendering backend. But we officially support only the Skia one.

This sounds to me as a contradiction. Since then there were no reason to remove them.

If the backends must be updated too often with every change in resvg and it is too time consuming, I think, there is a compromise: only the main skia backend can be used with git master, the other ones get updates rarely, e.g. monthly, but not later than until the next release.

Thank you for your work.

**Comment by RazrFalcon** [comment]
>removing all backends support except of one without any justification

https://github.com/RazrFalcon/resvg/issues/195

The problem with supporting other backends is not in keeping them up to date, but in fixing countless bugs. Not to mention performance differences. I'm using Skia not because it's easier, but because it's the fastest and the most correct one. There is no benefits in using other libraries like cairo.

And since resvg is still split into a preprocessor (usvg) and a renderer (resvg) the statement about multiple backends is still true. I'm simply not interested in supporting them. But someone else can, and quite easily.

**Comment by andreygursky** [comment]
> #195

Ah, here it is. Thanks. Really missing this reference in the commit message.

> fixing countless bugs (not in resvg, but in those libraries)

Any references to open issues in cairo and qt bugtracker?

> Not to mention performance differences. I'm using Skia not because it's easier, but because it's the fastest

Any reproducer source code?

https://github.com/RazrFalcon/resvg/tree/master/benches mentioned on https://github.com/jrmuizel/raqote/issues/78 is gone. From what I see there, cairo is almost always the fastest one.

> and the most correct one.

Can the correctness in respect to rasterizing be measured objective enough or do you mean with fewest important bugs?

> There is no benefits in using other libraries like cairo.

Since cairo is the standard for the whole gtk stack, there are indeed some benefits.

> I'm simply not interested in supporting them. But someone else can, and quite easily.

So another possible solution would be if you could move the code of the dropped relevant backends into separate repositories. Which could be cloned easy into resvg and resvg would discover them during build (or even better if a backend could be a plugin?). You wouldn't then maintain those repos, just supervise PRs from the potential joint maintenance efforts of those interested of having them. Anyway it would be useful to have the code now hidden somewhere in the git history in a repo as example.

**Comment by RazrFalcon** [comment]
>Any references to open issues in cairo and qt bugtracker?

For cairo, I didn't bother, so: #256, #233, #231, #36

For Qt: [QTBUG-72890](https://bugreports.qt.io/browse/QTBUG-72890), [QTBUG-76084](https://bugreports.qt.io/browse/QTBUG-76084), [QTBUG-83048](https://bugreports.qt.io/browse/QTBUG-83048), [QTBUG-72796](https://bugreports.qt.io/browse/QTBUG-72796), [QTBUG-67995](https://bugreports.qt.io/browse/QTBUG-67995), [QTBUG-65172](https://bugreports.qt.io/browse/QTBUG-65172) (this is the bugs I've reported during resvg development)

So yeah, I'm well aware of those libraries capabilities.

>Any reproducer source code?

https://github.com/RazrFalcon/tiny-skia/tree/master/benches

>From what I see there, cairo is almost always the fastest one.

1. https://github.com/RazrFalcon/resvg/blob/98989835f0732d9c50aff3ab6eb913c55ebe18d1/.github/perf-oxygen.svg
1. That was a crappy benchmark. Most of the time was spent on PNG generation.

>Can the correctness in respect to rasterizing be measured objective enough or do you mean with fewest important bugs?

Yes. See #256 + there is some differences in gradient stops processing. Also, Skia has a way better anti aliasing [technics](https://skia.org/dev/design/aaa). 

>Since cairo is the standard for the whole gtk stack, there are indeed some benefits.

Only if you are developing for GNOME, which I'm not. And still there are no benefits in using cairo. `tiny-skia` is smaller, better and faster. And after I'll finish porting it to Rust, it will also be easier to build and distribute.

>So another possible solution...

This is not a solution, because there was no problem in the first place. If you want to support a cairo resvg backend - go ahead. I'm all in. But I don't have time to do this.

**Comment by andreygursky** [comment]
> For cairo, I didn't bother, so ...

Thanks, I see now the label: https://github.com/RazrFalcon/resvg/issues?q=label:B-cairo

> For Qt: ... (this is the bugs I've reported during resvg development)

Great!

> https://github.com/RazrFalcon/tiny-skia/tree/master/benches

> https://github.com/RazrFalcon/resvg/blob/98989835f0732d9c50aff3ab6eb913c55ebe18d1/.github/perf-oxygen.svg

Thanks. So cairo is not that dramatically slower. For some use cases it would still matter, for others wouldn't.

For skia I see
```
    extra_cflags_cc=["-march=native" ...
```
In most GNU/Linux distributions cairo wouldn't be built in a such way. You've tested it with cairo built also with ```-march=native```?

> ... And after I'll finish porting it to Rust, it will also be easier to build and distribute.

Sure. The remaining integration issue with cairo@gtk is tracked in #318, I guess. In summary, this issue can be labeled WONTFIX and closed.

**Comment by RazrFalcon** [comment]
>So cairo is not that dramatically slower.

Blending with Screen is 13 times slower in cairo. Pretty dramatic.

I haven't published the results for gradients, but cairo is 2-3 times slower here too. Filling with a pattern is also [very slow](https://github.com/jrmuizel/raqote/issues/77), up to 35x in some cases.

[Here is](https://blend2d.com/performance.html) independent benchmarks.

> You've tested it with cairo built also with -march=native?

I'm sorry, but have you read the readme? It has an entire section just for build flags.

**Comment by andreygursky** [comment]
> Blending with Screen is 13 times slower in cairo. Pretty dramatic.

I mean overall. Some outliers for some cases are not uncommon.

> Here is independent benchmarks.

Thanks.

> It has an entire section just for build flags.

Sorry, now I see.

**Comment by RazrFalcon** [comment]
Good, then I'm closing this.
