### ISSUE TITLE
Selection of Renderer

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#379]
I tried to collected several svg2png-render on [SVG-renderer](https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites#more_untested_Render) 

[ImageMagick](https://imagemagick.org/index.php), [svgexport](https://github.com/shakiba/svgexport), [PhatomJs](https://phantomjs.org/) are imho often used, but SVG.NET, QtSvg, wxSvg are hardly listed

Is there a reason why you choose those you listed in [#svg-support](https://github.com/RazrFalcon/resvg/#svg-support), e.g. do they use a backed which is already tested?

**Comment by RazrFalcon** [comment]
>ImageMagick

Just a librsvg wrapper. They can do some basic rendering manually, but it doesn't worth considering.

>svgexport

This is Chrome. Same as resvg-test-suite/tree/master/tools/chrome-svgrender, but more user-friendly.

>PhatomJs

WebKit wrapper. The same as Chrome.

>Is there a reason why you choose those you listed

The libs and apps I've chose test rendering backends. There is no point in testing wrappers. The list you provide on wiki is a bit pointless, because there are like 5 decent SVG implementations (Chrome/WebKit, Firefox/Gecko, resvg, batik, rsvg and Inkscape). Everything else is either useless or just a wrapper.

>Svg-explorer-extension

This is just QtSvg

>cairosvg

Extremely primitive.

>svglib

Extremely primitive.

>aspose.svg

Proprietary.

>Trident

Dead? Proprietary?

>Presto

Dead. Proprietary.

>KSVG

Dead?

>Prince

Proprietary.

>Amaya

Dead

>Renesis Player

Dead

**Comment by JoKalliauer** [comment]
Thanks for clarifying, that's exactly the information I was looking for. (Sorry for bugging you, I was unable to find/understand the backend-information.)

**Comment by RazrFalcon** [comment]
No problem.
