### ISSUE TITLE
Add parse_doc_from_dom

### ISSUE THREAD

**Issue by zen3ger** [RazrFalcon/resvg#43]
Currently there's no function in the public API to go from `svgdom::Document` to `resvg::Document`. 

Adding this functionality would make it possible to create svg animations by modifying the `svgdom::Document` and  use `resvg` to generate a render tree which can be used with ie. `lyon` as mentioned [here](https://github.com/nical/lyon/pull/215).

**Comment by RazrFalcon** [comment]
It will be pretty slow. By I will add it anyway.

**Comment by RazrFalcon** [comment]
I just logged to say exactly the same =)

Yes, since 0.2 `RenderTree` (former `Document`) will be editable. It's still pretty low-level, but it will be the fastest way.

[This is](https://github.com/RazrFalcon/resvg/blob/0aded7de4d3d744a1da6d81f306179c19dd65a82/examples/draw_bboxes.rs#L57..L66) how it looks now.

**Comment by zen3ger** [comment]
Ah, thanks! I've been looking through the 0.1 docs and sources. I'll try this way. Anyhow, there might be some usecases when someone would like to go from `svgdom::Document` to `resvg::RenderTree` and probably won't hurt to add that function to the API. :)

**Comment by RazrFalcon** [comment]
Yes.

v0.1 is very outdated. Currently, the API is constantly being broken. It's 0.2-pre after all.
