### ISSUE TITLE
Possibility to take image buffer from memory instead reading file from disk following <image> "xlink:href" attribute

### ISSUE THREAD

**Issue by antmelnyk** [RazrFalcon/resvg#479]
🙌🏻 Hey and thank you for your hard work again!

As far as I see, there are 2 ways to read external image files in **_xlink:href_** attribute for `<image>` tag:
1. Use base64.
2. Use path to a local file.

Now, hear me out: would it be possible to use  **_xlink:href_** attribute that instead path would have some key by which we can read image buffer from memory directly, e.g. use existing Vec<u8> instead.

The use case is that I basically have an image buffer already and I construct SVG dynamically. To avoid encoding image to base64 (which can be huge for big images) or writing it to disk, I could just pass the already prepared buffer to `resvg`/`usvg` by key.

Implementation wise, it could be handled somewhere inside `get_href_data` function in `usvg/src/image.rs`.

I understand that it is probably totally out of scope since `resvg` library just follows SVG specifications, but I would love to hear what author thinks about it. 🙏🏻  Maybe it's all is overkill and I should just transform image to base64?

**Comment by RazrFalcon** [comment]
Base64 is plenty fast. The issue is that you have to encode your image into PNG, which is very slow. And then we would have to decode it back.

The obvious solution would be not to use large raster images in SVG to begin with. And cache base64 data for small one.

A more general solution would be to allow providing a custom `href` resolver. This way a library user could add a proper url support. Right now, resvg would not do any network requests, which is allowed by the spec (yes, `href` can store an actual URL).
So you would have some sort of callback/trait that would expose `href` value when it's not a data-url and you could chose what data to provide. The default implementation would support only local fs.

The problem is that `usvg` would still store a PNG and not a raw data buffer. And I don't think adding image decoders to `usvg` is a good idea.

**Comment by antmelnyk** [comment]
>A more general solution would be to allow providing a custom href resolver. This way a library user could add a proper url support. Right now, resvg would not do any network requests, which is allowed by the spec (yes, href can store an actual URL).
So you would have some sort of callback/trait that would expose href value when it's not a data-url and you could chose what data to provide. The default implementation would support only local fs.
Nice, exactly that, custom resolver was one of the ideas how to handle that.

>The issue is that you have to encode your image into PNG, which is very slow. And then we would have to decode it back.
I'm not following, but what if my image buffer is already not raw, but encoded PNG/JPEG? As far as I see in code, `resvg` reads the file and puts it inside data of `ImageKind` without any encoding, so it already uses PNG "as is". In my case, buffer preparation is handled outside of resvg. And why do we need to decode it back?

**Comment by RazrFalcon** [comment]
Resolver would be implemented in `usvg` crate, which doesn't support PNG/JPEG. It simply loads a file or base64 data into the memory. `resvg` then decodes it.
So you would be able to provide only PNG/JPEG encoded data, not raw pixels.

We could technically add an additional `ImageKind` just for this case. But again, you would have to clone your data. Maintaining a reference would be close to impossible. But we might use `Arc<Vec<u8>>` or something like this.

**Comment by dmtrKovalenko** [comment]
It actually makes a lot of sense if you need to render millions of same svg templates that rendering specific image.
