### ISSUE TITLE
Emoji's (and other unicode characters) not rendering

### ISSUE THREAD

**Issue by dmtrKovalenko** [RazrFalcon/resvg#485]
When rendering any text with svg it fails to render with unknown symbols.

```svg
 <text
   font-size="64"
   dominant-baseline="middle"
   text-anchor="middle"
 >
   I made this video entirely with Rust 🦀
</text>
```

![image](https://user-images.githubusercontent.com/16926049/144084853-e7986f7b-809a-4716-a365-be6a1e726c06.png)

**Comment by RazrFalcon** [comment]
Yes, only vector glyphs are support. No bitmap, SVG (paradoxically) and palette based fonts. 
I thought I had an open issue for this, but looks like I don't.
It's not _that_ hard to implement, but still will require some extensive work.

This is mainly because we have our own text layout implementation. And because there are no viable alternatives anyway.

**Comment by RazrFalcon** [comment]
As for the bug itself - you probably chose a weird font. By default it should work just fine.

**Comment by dmtrKovalenko** [comment]
I tried a lot of combinations of different font, starts from `sans-serif` ending with wrapping emojies with their own `<tspan font-family="Apple Color Emoji" />` (I am using macos) – nothing works and whole text renders as unkown

**Comment by RazrFalcon** [comment]
Strange. I guess it fails to fallback to a different font. Removing the emoji symbol helps?

**Comment by dmtrKovalenko** [comment]
Yes, removing emojis helps and all other text renders correctly

**Comment by RazrFalcon** [comment]
Ok, this is a know issue then. The current font fallback algorithm is pretty dumb.
Basically, the problem is that this string has to be rendered using two fonts: regular one and one with emoji. resvg doesn't understand this yet, so it fails.

I've split this issue into following one: #486 #487

Sadly,  I don't really have time to work on it. It would be ready when it would be ready.
You can try using headless chrome or librsvg in the meantime. They do support emojis (sort of). But you will [sacrifice](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#e-text) a lot too.

**Comment by corradio** [comment]
Hello @RazrFalcon,
Is there any news regarding emoji support?

**Comment by RazrFalcon** [comment]
@corradio Not in the near feature. Maybe in a year or two. See #487

**Comment by corradio** [comment]
Noted. Let me know in #487 if I can help.
