### ISSUE TITLE
How to set DPI in the minimal example

### ISSUE THREAD

**Issue by topochico-one** [RazrFalcon/resvg#526]
Is it possible to set dpi for the output png file in the [minimal example](https://github.com/RazrFalcon/resvg/blob/master/examples/minimal.rs)?

Adding `opt.dpi = 300.0;` on line 12 did not seem to affect the output.

I am sorry for such a basic question. I am completely new to resvg and image processing in general.

**Comment by RazrFalcon** [comment]
I should improve `Options::dpi` docs... What result do you expect from this setting? This option doesn't "scale" the image (you should use `--zoom` instead). This option doesn't affect DPI of the produced PNG.
All it does, is affects how relative units (cm, in, etc.) would be converted into pixels. That's it.

**Comment by RazrFalcon** [comment]
It's not possible and doesn't really makes sense. Why would you want this?

**Comment by topochico-one** [comment]
I am sorry -- I know very little about these things. I just want to generate sharper PNGs. For example, when I export my artwork in Adobe Illustrator, I can set image resolution by specifying PPI. I want to be able to do the same for the artwork I generate programmatically in Rust.

**Comment by RazrFalcon** [comment]
PNG is a raster format, it has a fixed "resolution". I'm not sure how Illustrator loads PNGs and if it cares about the DPI property, but you can try rendering your SVG at higher resolution. Like `--zoom 4` via CLI or `usvg::FitTo::Zoom(4.0)` via code.

While PNG indeed has a "resolution"/DPI property, it has noting to do with SVG DPI and cannot be written at the moment anyway, because the `png` crate doesn't support it.
