### ISSUE TITLE
Would it be feasible to turn patterned fills into paths, too?

### ISSUE THREAD

**Issue by hmeine** [RazrFalcon/resvg#553]
I am having rendering problems with https://github.com/Weasy666/bevy_svg which uses usvg + lyon. One of the problems seems to be that the files I am looking at use patterned fills, see example attached to https://github.com/Weasy666/bevy_svg/issues/19

I looked for a way to get rid of patterned fills, replacing them with paths, much like the usual "convert object to paths" action.  However, this seems to be a much-sought feature that does not exist yet:
* https://stackoverflow.com/questions/62645102/render-an-svg-polygon-with-a-pattern-fill
* https://graphicdesign.stackexchange.com/questions/110719/how-do-i-convert-a-svg-patterned-fill-to-a-set-of-paths
* https://superuser.com/questions/1507049/inkscape-convert-fill-pattern-to-path

According to the superuser post, there are two options:
* (lossy) conversion to PNG and back
* using Microsoft's PDF Printer and converting back to SVG (usually, PDF exports retain patterns, I tried that)

From reading usvg/resvg's description, this feature sounded as if it could be implementable and not totally out of scope?

(I hoped that MicroSVG would not support patterns, but it does. ;-) Alas, bevy_svg does not.)

**Comment by RazrFalcon** [comment]
Well, MicroSVG is designed to be 100% lossless. Meaning it must simplify, but not break the input, at least visually. Which is pretty hard. One of the recent issues: #550

As for patterns, they are a constant problem. They are surprisingly hard to implement. See #539 #507 #395 #221 #392
Currently, resvg renders them to raster and then uses this raster image as fill/stroke. This is the most common technique. It's very fast, rendering wise, but introduces a lot of issues. Mainly the fact that out pattern has integer size now, which is not true for a source SVG. I haven't found a solution yet.

As for your task, well... It's kinda impossible?! To implement pattern fill, we have to use a shape as a clip path and then fill it with a pattern manually. In most cases it would be very slow and doing so on the usvg side would produce a very large SVG.
Stroking is even worse, because a stroked path usually has an enormous amount of segments. Not to mention that usvg doesn't do stroking at the moment. resvg/tiny-skia does.
And I can only imagine how many weird issues would araise from this.

So my suggestion would be to tile patterns manually on your side since I don't see a robust way of implementing this on the usvg side.

PS: the usvg goal is to produce an SVG simple enough for resvg/tiny-skia. Not the most simple in general.

**Comment by hmeine** [comment]
Thanks. Yes, I already suspected that it must be very difficult, given that nobody seems to have implemented it in any software on any platform so far.  The marker issue is very interesting and enlightening, indeed.  Will close this issue, then.
