### ISSUE TITLE
Bump `png` crate?

### ISSUE THREAD

**Issue by AntoniosBarotsis** [RazrFalcon/resvg#571]
I came across an issue with a crate that lists this one as a dependency, specifically with the `png` crate version as I was using a later one.

I see that you've [added some comment](https://github.com/RazrFalcon/resvg/blob/8fd60e7d3725112ee26b96045817bdc668dba797/Cargo.toml#L24) but I'm not sure what that means 😅 .

I was also wondering if you *need* the Lockfile as according to the [Cargo book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock):

> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put `Cargo.lock` in your `.gitignore`.

Thanks in advance!

**Comment by RazrFalcon** [comment]
Yes, this is the exact `png` version that should be used.

As for `Cargo.lock`, `resvg` guarantees reproducible results, which are only possible by locking dependencies.

**Comment by xStrom** [comment]
There are three issues with this pinning of `png`.

First, the rationale for doing it (*pin version to match flate2 miniz_oxide version*) doesn't seem to be true anymore. `flate2` depends on `miniz_oxide` `^0.6` [since Sep 6, 2022](https://github.com/rust-lang/flate2-rs/pull/317), as does `png` [v0.17.7](https://github.com/image-rs/image-png/blob/master/CHANGES.md#0177). However the pinned `png` v0.17.6 depends on `miniz_oxide` `^0.5`, so the pinning achieves in fact the opposite of what it claims. (*Unless there is some `flate2` pinning happening somewhere deep?*)

Second, the way cargo works means that any dependency doing pinning enforces that pin for every other crate wanting the same major version. We ran into this issue at [druid#2345](https://github.com/linebender/druid/pull/2345) where we had to revert `resvg` back to v0.25 because cargo would refuse to build, because another dependency required the latest bugfixes from `png`.

Third, because the pinning propagates all the way up the stack of crates, it prevents bug and security fixes from arriving via `cargo update`. That is, if the `png` dependency in `resvg` would be bumped to `=0.17.7` then cargo would build `druid`. However any application depending on `druid` would be stuck with `png` v0.17.7. If an importat fix comes out as say v0.17.8, then the deep dependency on `resvg` would prevent this from being used in this app.

Thus I would recommend removing the pinning and changing the dependency to `0.17.7` (which is `^0.17.7`). This would ensure that both `png` and `flate2` (currently) depend on the same `miniz_oxide`, and also crucially wouldn't prevent `png` fixes from being used higher up the stack.

**Comment by AntoniosBarotsis** [comment]
I experienced a similar issue where I wanted to keep the png crate at the latest version but couldn't because of the lock but I guess I wasn't explicit enough 😅

Technically speaking, any new patch version should not include breaking changes so indeed the suggestion above should work.
