### ISSUE TITLE
[usvg] add means to access a node's original attributes 

### ISSUE THREAD

**Issue by abey79** [RazrFalcon/resvg#588]
I work on project which needs exactly the SVG "normalisation" offered by `usvg`. However, I would also like to support Inkscape semi-official layer extension, in which top-level groups can serve as layer with specific attributes.

Here is an example:
```svg
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     baseProfile="tiny" height="15.875cm" version="1.2" viewBox="0 0 600.0 600.0" width="15.875cm">
  <g fill="none" inkscape:groupmode="layer" inkscape:label="3-hello" stroke="#00f" style="display:inline">
    <polygon points="10.0,10.0 10.0,210.0 210.0,210.0 210.0,10.0"/>
  </g>
  <g fill="none" inkscape:groupmode="layer" inkscape:label="2-world" stroke="#080" style="display:inline">
    <polygon points="400.0,400.0 400.0,700.0 600.0,700.0 600.0,400.0"/>
  </g>
</svg>
```
Here, both groups are Inkscape layers, one whose label is `"3-hello"` and another is `"2-world"`. In my project, I would need to access these attributes in order to figure out if a given top-level group should be considered a layer.

Is there a way to achieve this? If not, could this be added? For example via one of these approaches?
1) Add a field in `Node` to store all unresolved attributes, e.g. in a HashMap. This would need to be conditionally compiled in a feature to avoid unneeded overhead.
2) Add a reference to the original roxmltree node in `Node`, so that the roxmltree API can be used to extract attribute values.

**Comment by RazrFalcon** [comment]
This is not supported and not planned. usvg parsing involves an enormous amount of post-processing, so the final `usvg::Tree` often has very little to do with the original data. And preserving any information about the original document is way to hard. Even the `id` attribute preserving is already a challenge.

I understand that this feature might be useful to some, but this would require an enormous amount of work.
usvg works with SVG, not SVG supersets.

**Comment by RazrFalcon** [comment]
Just to illustrate: 

1. We have to make sure our "reference" to the original XML node will survive all the transformations. This requires a lot of testing.
2. We have to parse all those non-standard attributes in some meaningful way.
3. We would have to support not only Inkscape.
4. Non-standard attributes might expect a specific XML tree structure, which usvg would have to follow.

And so on and so on...

**Comment by abey79** [comment]
Thank your the feedback. I understand that this would be a deviation from the focus on rendering, and the balance between increasing "lateral" usefulness and complexity is tricky to deal with. That said, given the ubiquity of inkscape's layer extension, and precisely because of the extended tree manipulation usvg does, it might be worth considering an ad hoc support for this specific extension—as opposed to some general, blanket support for all possible extensions.

From this perspective, I respectfully disagree on some of your points:

> 1. We have to make sure our "reference" to the original XML node will survive all the transformations. This requires a lot of testing.

Though I initially suggested it as a possibility, I don't think keeping a reference of the original tree is required. The `Group` struct could simple include additional fields capturing the the semantics of Inkscape layers.

> 2. We have to parse all those non-standard attributes in some meaningful way.

Yes, there would be additional parsing involved. But `inkscape:groupmode` can only have `group` or `layer` values, and `inkscape:label` is just a string to store.

> 3. We would have to support not only Inkscape.

I think ad hoc support for a specific extension—or even part of it—because of its ubiquity, would be acceptable. 

> 4. Non-standard attributes might expect a specific XML tree structure, which usvg would have to follow.

In general yes, but if this is framed as ad hoc support, then this depends on the specific extension being supported. In the case of layers, I don't think this is the case.

Anyways, Inkscape layer support is a strong requirement for my use case, so I will have to figure out a solution. Given how well usvg otherwise fits my needs, my first course of action will probably be to try and implement what I suggest here. I'll make sure to let you know of the results should that happen.

**Comment by RazrFalcon** [comment]
I'm not keen about a half-baked solution. Storing `roxmltree::NodeId` "references" just for groups? Why so? Why not every element? It's only more confusing.

Again, you underestimate how much post-processing is involved in `usvg`. Making sure that the `id` attribute would survive those transformations is already a challenge. 

Also, adding any kind of SVG-extensions is out of scope. So parsing `inkscape:*` attributes is no go.
As of now, usvg doesn't parse non-SVG attributes at all. And it would be really hard to do otherwise.

I understand that you need an Inkscape-specific solution, but it opens a door for other extensions and I have no time or plans on dealing with them.

I don't see an easy solution for your problem, if any. So this is a _no_.

Just in case, this is how usvg works:

1. Parse XML into `roxmltree`
2. Convert `roxmltree` into `rosvgtree`. No CSS, no `use`, no non-SVG elements and attributes already
3. Convert `rosvgtree` into `usvg::Tree`
4. Post-process `usvg::Tree`

I would say that this is simply impossible by design.

**Comment by abey79** [comment]
> I'm not keen about a half-baked solution. Storing `roxmltree::NodeId` "references" just for groups? Why so? Why not every element? It's only more confusing.

At this point, this is no longer what I have in mind. Instead, I'm thinking of adding a `layer` field to `usvg::Group`, that would be an enum with either `Layer(&str)` or `Group` (or something of that sort).

This would probably require whitelisting `inkscape:groupmode` and `inkscape:label` in `rosvgtree` and dealing with it in `usvg`.

Of course, I perfectly understand if you think this is too ad hoc to be integrated—I can live with the idea of a permanent fork. As I mentioned, there is no way around this feature for my project, so it's either this, reimplementing from scratch most of `usvg` functionality on top of `roxmltree` or the `svg` crate, or some other avenue I have yet to identify 😅

**Comment by abey79** [comment]
FYI, here is how I've implement what I need: https://github.com/abey79/resvg/pull/1

**Comment by tatarize** [comment]
@RazrFalcon this seems in error.

You would only provide a giant bag of stuff that wasn't parsed. This was an attribute, but it didn't mean anything so here's a list of them and their string values. Otherwise if they are completely stripped, there's no way to recover them. You do not need to parse them beyond saying here's a list of trash I found attached to the svg.


> 1. We have to make sure our "reference" to the original XML node will survive all the transformations. This requires a lot of testing.

Strings survive whatever transformations you apply to them, though admittedly there may not be a 1:1 dom node to object created in the list there.

> 2. We have to parse all those non-standard attributes in some meaningful way.

You wouldn't. That's not your job. But, providing the values to the end users seems like it would be. 

> 3. We would have to support not only Inkscape.

You don't. This is part of the SVG spec. You'd only need to implement the spec.

https://www.w3.org/TR/SVG11/extend.html Just give the user a big list of unknown keys and values. If they need to parse that they can do that.

> 4. Non-standard attributes might expect a specific XML tree structure, which usvg would have to follow.

They are not allowed to expect that. That's defined with the dom and svg spec.  And so long as the data is handed over to the other package, if they wanted additional parsing they could do that on their own. You are not required to do parsing beyond the SVG spec, and pass through the other foreign values.

But, this request is largely I have foreign keys and objects and I need them parsed like an xml parser would parse them but attached to the objects you produced. --- There's a lot of tweaks to svg for various other formats and stripping that data rather than providing a garbage dump of that data means this library can't be used for anything greater than that.

**Comment by tatarize** [comment]
It wouldn't need to be a list either, you could just add in a json string of the stuff that was part of this node but wasn't seen as SVG. Here's the pile of stuff updated from parents, here's the pile of attributes from this node in particular. Do whatever you want with that.

**Comment by RazrFalcon** [comment]
@tatarize This is not a `usvg` job. Out of scope. You're free to fork it.
