### ISSUE TITLE
Is it possible to write the simplified output of usvg to an .svg file?

### ISSUE THREAD

**Issue by Legonaftik** [RazrFalcon/resvg#595]
Sorry, I'm not familiar with Rust but I found the project very useful 🙏 

As I can see, the output of `usvg` is a simplified in-memory representation of SVG as a tree so it can be used with any SVG renderers. 
However is it possible to write this simplified SVG back to some `.svg` file instead?

**Comment by RazrFalcon** [comment]
It was supported until recently. See #568

The short answer is that since recently we have to write text back, which is extremely hard. And I have no time working on it.

Overall, it's really hard to write the `usvg::Tree` back to SVG. And getting only harder. 
It might be supported someday, but for now - no.

**Comment by RazrFalcon** [comment]
Here is the recent discussion: https://github.com/RazrFalcon/resvg/issues/569#issuecomment-1441953903

**Comment by Legonaftik** [comment]
Thank you for such a quick and actionable response 🙏
