### ISSUE TITLE
incorrect transform of `use`d symbols

### ISSUE THREAD

**Issue by burrbull** [RazrFalcon/resvg#610]
It looks like if `use` has `transform` attribute this attribute applies twice.

**Comment by RazrFalcon** [comment]
Can you provide an example?

**Comment by burrbull** [comment]
For example:
```xml
<svg height="150" width="150" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
<symbol id="R">
<rect height="15.118111" style="fill:none;stroke:#000000;stroke-width:1.12" width="37.795277" x="-18.897638" y="-7.5590553"/>
</symbol>
</defs>
<g id="e1" transform="translate(50,50)">
<use id="Re1" transform="translate(18.897638,0)" xlink:href="#R"/>
<path d="M37.795277,0,52.913387,0" style="fill:none;stroke:#000000;stroke-width:1.12"/>
<path d="M0,0 L-15.118111,0" style="fill:none;stroke:#000000;stroke-width:1.12"/>
</g>
</svg>
```

What was expected:
![изображение](https://user-images.githubusercontent.com/3072754/230739062-8d9813e7-a2c0-4a0e-9aa4-2a1ed19819ca.png)

resvg rendered:

![example](https://user-images.githubusercontent.com/3072754/230739080-bf086370-66d9-490c-b814-4a43f843e10c.png)

**Comment by RazrFalcon** [comment]
While resvg is definitely wrong, your file would not be rendered as you expect by any app except Inkscape:

![use-ts](https://user-images.githubusercontent.com/725494/230739329-ffb52250-09ac-497a-8604-61da10b72415.png)

I'm still trying to figure out what is going on. In general, I would avoid `symbol` as a plague. It's very poorly documented and supported.

**Comment by RazrFalcon** [comment]
Yes, `resvg` duplicates the transform, which is a bug. But it would still be an incorrect output.

**Comment by RazrFalcon** [comment]
It's hard. The correct way to use `symbol` is to define the `viewBox` attribute and control the actual size by setting `width`/`height` on `use`. Like so:

```xml
    <defs>
        <symbol id="R" viewBox="0 0 37 15">
            <rect style="fill:none;stroke:#000000;stroke-width:1.12" width="37" height="15"/>
        </symbol>
    </defs>
    <use id="Re1" transform="translate(0,-7)" xlink:href="#R" width="37" height="15"/>
```

This would still be rendered incorrectly, since `viewBox` would be used as a clipping mask, so stroking would be clipped.

And because `symbol` always rendered with a clipping rect and you move the rectangle inside the symbol in your original code - the proper implementation clips it out and leaves only the quarter of the rect.

So technically resvg has two bugs here: double transform + missing clip. We do support symbol clipping, but it wasn't applied here for some reason.

And while we do  have 14 `symbol` tests in our test suite - it's not enough in the bizarre world of SVG.

For now, simply do not use `symbol` and link `rect` or `g` directly.

**Comment by RazrFalcon** [comment]
We actually do have a test with `transform` on `use`, but to trigger the bug, `use` must not define `width`/`height`.

**Comment by RazrFalcon** [comment]
Both bugs are fixed now.
