### ISSUE TITLE
Implement inline-size for SVG 2

### ISSUE THREAD

**Issue by pennomi** [RazrFalcon/resvg#643]
For my current project, I need an SVG renderer with text wrapping support, and Inkscape is the only one that I can find. I think adding support for SVG 2's inline-size would be the simplest way to do that.

I'm happy to take the time to do this myself and make a pull request, but I would need a little nudge in the right direction since I've never written Rust and I don't know this codebase well. Alternatively, I'd be happy to pay a bounty for this feature to be added.

**Comment by RazrFalcon** [comment]
This is part of #443

This issue has two main problems:
1. As you already noticed, no one supports it. Inkscape tries, but it's still very primitive. Meaning that no one knows how it should be implemented. Even the SVG spec authors. It would require an absurd amount of testing, aka time.
2. I have no time working on it. Even working full-time it would take months.

And I don't think someone else would able be implement it. Even I find the current text layout implementation confusing.
It's really-really hard to do.

And even before supporting `inline-size`, we have to first support `white-space`, `word-break` and `line-break`, since SVG 1 operates on single-line text. Which would require even bigger changes. And I don't even want to think about hyphenations.

So... my suggestion would be to simply gave up on this idea. Find another way.

**Comment by pennomi** [comment]
Ha, fair enough! SVG just doesn't seem to be made for wrapping text.

**Comment by RazrFalcon** [comment]
Most SVG libraries struggle even with SVG 1 Text features, including resvg. It's absurdly complicated. 
I would even go as far as to say that SVG 2 Text is simply impossible to implement. After all, no one was able to implement even SVG 1 Text in 20 years. And SVG 2 is times more complicated.

Heck, there is no even `line-height` concept in SVG 1/resvg. Which had to be implemented before `inline-size`.

Your only option is to wrap text on your side.
