### ISSUE TITLE
Add render_to_pdf to the backends

### ISSUE THREAD

**Issue by mseri** [RazrFalcon/resvg#65]
How hard would it be to implement render_to_pdf to the backends, specifying (or inferring) a size (and preserving the aspect ratio)?

**Comment by RazrFalcon** [comment]
Currently, the library is designed to render raster images, so PDF is a bit of problem.

Technically it's possible, but there are some problems:
1. SVG cannot be directly translated to the PDF, because of advanced features like clipPath, mask, filters, etc. See [Backend requirements](https://github.com/RazrFalcon/resvg/blob/master/docs/backend_requirements.md). Not sure that PDF supports all of this. So this backend will not be lossless.
1. I don't know anything about the PDF internals.

Also, it's already kinda supported:
```cpp
#include <ResvgQt.h>

QPrinter printer(QPrinter::PrinterResolution);
printer.setOutputFormat(QPrinter::PdfFormat);
printer.setPaperSize(QPrinter::A4);
printer.setOutputFileName("test.pdf");

ResvgRenderer renderer("test.svg");

QPainter p(&printer);
renderer.render(&p);
```

But in most cases it will create PDF with just a single raster image, because of  №1

**Comment by mseri** [comment]
I see. I thought that something like `rsvg-convert -f pdf` in `librsvg` could have been possible by using the right surface backend from `cairo`, somewhat similarly as in your Qt example. In that case however it converts the svg to a vector pdf, although potentially in a lossy way.

From what I read from the backend requirements, I think that after all a lossy vector conversion could be implementable but it would require figuring out the various elements. It's not super urgent, but I am reimplementing the reMarkable tablet scripts in rust to try and have a cross-platform single executable. I may give it a go sometimes in the future, because the svg->vector pdf conversion is one of the few missing bits.

**Comment by RazrFalcon** [comment]
Yes, the same can be done to the cairo backend. I don't really know how it works in the `librsvg`, because it doesn't have a PDF-specific renderer and still produce a correct result. Have to investigate this.

At the moment, I'm using a lot of raster buffers for layers, so it will not work anyway. So I have to find a way to 'fix' existing backends to support the PDF output.

I think that implementation of a PDF-specific backend will lead to a better control and results. But it requires raster features anyway. So it should be done on top of the existing backends.

So, it's a really hard question and I need time to investigate this.

**Comment by mseri** [comment]
Ok, thanks for the detailed explanation!

**Comment by Rush** [comment]
If skia is the only backend, wouldn't it be possible to export to PDF via skia?

**Comment by RazrFalcon** [comment]
Nope, because PDF generation requires a different rendering pipeline from what is used currently in resvg. We need a dedicated PDF generator, which is an enormous amount of work.

**Comment by RazrFalcon** [comment]
Out of scope.
