### ISSUE TITLE
Path with gradient stroke

### ISSUE THREAD

**Issue by Dherse** [RazrFalcon/resvg#657]
Hello,

Recently, I have been implementing color gradients in [typst](https://github.com/typst/typst). I am currently using resvg to convert from output SVGs and compare them with the (expected) PNG outputs. While trying RGB gradients on strokes, I have discovered the following error: in Chrome, Firefox, and resvg, the path is not shown at all when its stroke is set to a gradient as can be seen in the following files:

![test](https://github.com/RazrFalcon/resvg/assets/9665250/64d9b5bf-b53e-4f67-a4b8-e4bfea85fdbf)

PNG output:

![test](https://github.com/RazrFalcon/resvg/assets/9665250/135d4fde-6245-4f49-9da8-473bc3ca5b87)

However, by simply changing the line from the path `M 0 0 L 50 0` to `M 0 0 L 50 0.00001` as can be seen in the following file, then it works:

![test](https://github.com/RazrFalcon/resvg/assets/9665250/3f902cf6-bacf-42d1-8afa-94af637ce047)

Which gives the following PNG output:

![test](https://github.com/RazrFalcon/resvg/assets/9665250/276ebbcc-6753-448c-ba90-1f85359cfa00)

At this point, it is very unclear to me where this behaviour comes from, is it a bug in all three readers (note that it works in Inkscape). Could this be simply undefined behaviour? Am I misunderstanding the specifications? Or is it an edge case not covered in all three aforementioned readers?

Thanks in advance for your answer,

I look forward for any insight you might have,

Sébastien

PS: there are no warnings, no errors, no panic. None of the readers gives any log messages either.

**Comment by Dherse** [comment]
To add to the discussion @LaurenzV, suggested using `gradientUnits="userSpaceOnUse"` which is convenient because it works, but it's inconvenient because it requires knowing the user space then. It's interesting that it appears to be an issue of the path having a width zero which leads to it "not having an `objectBoundingBox` :(

**Comment by RazrFalcon** [comment]
This is correct. By the SVG spec, a gradient or a pattern with `objectBoundingBox` cannot be set on a shape without a bbox. And a horizontal line or a vertical line do not have a bbox, since either width or height are zero.

You can verify it by using `stroke="url(#fC771C26CF7DBF8CF23B923A118C737A7) red"` and a proper SVG library would draw a red stroke, as it should by the spec.

I'm not sure how it can be solved. You either use `userSpaceOnUse` or outline the stroke on your side, to make it into a "rectangle". 

PS: this is why you cannot clip, mask or filter hor/ver lines with `objectBoundingBox` as well.

**Comment by Dherse** [comment]
Thank you very much for your answer, we ended up using `userSpaceOnUse` and reworking generation :)

> You should never use Inkscape as a reference. Only Chrome.
I can feel this, it has been a pretty big chore trying to get SVGs generated by typst to render correctly in Inkscape.
