### ISSUE TITLE
Linking C library in Windows

### ISSUE THREAD

**Issue by makarr** [RazrFalcon/resvg#658]
I've been using the C API on Mac and Linux without issues but when I try to link on Windows I get "unresolved symbol" errors that seem to refer to Windows system libraries. With `rustup==1.72.0` I get 32 errors, while with `rustup==1.69.0` I get 29 errors, so maybe the problem lies on their end. I am making sure to set the RUSTFLAGS env variable following a [previous issue](https://github.com/RazrFalcon/resvg/issues/346#issuecomment-767183467).

Meanwhile I can build and run `resvg.exe` on Windows without any problems. Perplexing! 

I setup a simple test repo here: https://github.com/makarr/resvg_lib_test

Even if the fault does not lie with `resvg` I would be thrilled if someone could explain how to get the C API to work on Windows.

**Comment by RazrFalcon** [comment]
I don't know what you're building and how, but here are the Win libraries `tools/viewsvg` links:

```
-lWs2_32 -lAdvapi32 -lBcrypt -lUserenv -lNtdll
```

I do plan to write build instructions eventually: #564 But I'm not using Windows, so I'm not sure what happens in your case. I would assume you have to link Win libraries (for some reason) required by Rust std, because `resvg` by itself doesn't need any.

**Comment by makarr** [comment]
Steps to build resvg C library:
1. Install Rust on Windows 10. (Rust version 1.72.0)
2. `git clone https://github.com/RazrFalcon/resvg.git`
3. `cd resvg/c-api`
4. `$ENV:RUSTFLAGS = "-lWs2_32 -lAdvapi32 -lBcrypt -lUserenv -lNtdll -C target-feature=+crt-static"`
5. `cargo build --release`

Steps to reproduce issue:
1. Install CMake (>= 3.22) on Windows 10
2. `git clone git@github.com:makarr/resvg_lib_test.git`
3. Copy `resvg\target\release\resvg.lib` to `resvg_lib_test\resvg`
4. `cd resvg_lib_test`
5. `cmake -S . -B build`
6. `cmake --build build`

**Comment by RazrFalcon** [comment]
You have to link those libs to your executable, not to Rust/`resvg`. For some reason, afaiu, Rust doesn't propagate those library dependencies to the final binary. Maybe because of Windows, maybe because you use  static linking. I don't know. I don't have Windows to test it.

You might want to ask about it in Rust/Cargo repos. This is not a resvg issue, but rather the way Rust build C libraries on Windows.

**Comment by makarr** [comment]
You're 100% right. Fixed it by linking the Windows system libraries in CMake. Closing the issue.
