### ISSUE TITLE
Please reconsider making `calculate_bbox` include stroke bbox

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg#662]
I think it's only correct in versions prior to [v0.34.0](https://github.com/RazrFalcon/resvg/blob/master/CHANGELOG.md#:~:text=usvg%3A%3Anodeext%3A%3Acalculate_bbox), which is consistent with the returns in Firefox.

![image](https://github.com/RazrFalcon/resvg/assets/2784308/8a34eecd-8bea-4f1c-ab50-8a00848edc02)

resvg-js relies on the bbox information returned by the `calculate_bbox` API, which will cause serious incompatibilities when we upgrade. Can this be re-supported?

See: https://github.com/yisibl/resvg-js/pull/258/files#diff-aceed9dd71f2a53f7ad24cb97fc3c387bd1726d239591f9b85a11d52ade9ea9c

![image](https://github.com/RazrFalcon/resvg/assets/2784308/4e9f3825-ed84-43c7-a643-67fddc135187)

```svg
<svg viewBox="-40 0 180 260" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g fill="green" transform="rotate(-10 50 100) translate(-36 45.5) skewX(40) scale(1 0.5)">
    <path id="heart" d="M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z" />
  </g>
  <use xlink:href="#heart" fill="none" stroke="red" stroke-width="1" />
</svg>
```

**Comment by RazrFalcon** [comment]
I assume you're looking for [SVGGraphicsElement.getBBox](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox) JS API?
It will be extremely expensive to call. I will think what can be done here, but it's hard. It's a surprisingly complicated task.
We technically do calculate the "total bbox" (aka fill + style + filter) in the `resvg` internals, but it's not part of public API and would be hard to expose.

PS: and while we did in fact included the stroke before, the algorithm was garbage.

**Comment by yisibl** [comment]
Yes, resvg-js is emulating an `SVGGraphicsElement.getBBox` like API, which is already in use in the actual product.

Judging by the results, previous versions of `resvg` have done a pretty good job, and I look forward to you bringing this API back.

Thanks again for all your work, it helps me a lot.

**Comment by RazrFalcon** [comment]
I'm a bit confused about the image you have provided. Not only the stroke is ignored, but it also shifted. Is this expected?

**Comment by yisibl** [comment]
The screenshots may be a bit questionable, the actual expected results can be tested [here](https://resvg-js.vercel.app/).
![image](https://github.com/RazrFalcon/resvg/assets/2784308/1f988eb3-5156-4dc2-b624-b6fef38a1e0b)

**Comment by RazrFalcon** [comment]
Done.

**Comment by yisibl** [comment]
Thanks!

**Comment by RazrFalcon** [comment]
Let me know if works as expected.

**Comment by yisibl** [comment]
How much will the `bbox` cost of calculating stroke increase in the new API?

**Comment by LaurenzV** [comment]
I also had to resort to a custom bbox calculation (basically copied from old resvg) for [svg2pdf](https://github.com/typst/svg2pdf), will try it out later!

**Comment by LaurenzV** [comment]
Happy to report that it not only works flawlessly, but changing to your implementation even made me find two wrong test references images in the repository and also fixed an annoying bug in the library, so thanks! :D

**Comment by RazrFalcon** [comment]
@yisibl Depends on what you're doing. If you're querying `usvg::Tree` info and then rendering it - nothing. Because I just moved bbox calculation from resvg to usvg. I was calculating it before already.

Otherwise, idk. I haven't run any benchmarks. It's not the fastest operation for sure, but unless you have paths with tens of thousands of segments - it shouldn't be noticeable.

There are a couple of ways to optimize stroke bbox calculation, but this would require a lot of work.

PS: if you're asking about the `Node::stroke_bounding_box` method specifically - it's free. All bboxes are already calculated.

**Comment by RazrFalcon** [comment]
@LaurenzV glad to hear. The old `resvg` implementation was an approximation/a guess work. It was fast, but flawed. The new one (since v0.34) is correct, but slower.
And I know it is correct, because object and stroke bboxes are both used during rendering, therefore are heavily tested.

Ideally, we should rewrite `tiny-skia`'s path stroking algorithm to a callback based one. So we would be able to skip new path allocation. But it's far from trivial. Stroking is a very complicated process.

**Comment by LaurenzV** [comment]
I have another small question. I know the answer will probably be that it's not possible, but I still figured I might ask.

Basically, I am trying to add support for filters in `svg2pdf`. Since PDF has no way of representing those, my plan was to just render any groups that have filters into an image using resvg, and then just embed the rasterized image into the PDF. 

I tried it by basically creating a new pixmap with the size of the stroke bounding box and then calling `resvg::Tree::from_usvg_node(&node)` and it works well in most cases! But the problem I'm facing is that some filters will have graphical effects that exceed the bounding box of the object they are applied to (such as for example gaussian blur as well as `feFlood`), meaning that they will be cut off from the image. Is there any way I can take these into consideration?

The only option I see is to just allocate a huge region (like 2x or 3x the original size) so that at least in practice this will never cause any problems, but this will obviously 1) make everything a lot slower and 2) still not technically be correct, since I don't think there is an inherent limit on how far away a filter can have an effect. So if the SVG is weird enough, this will produce wrong results.

Any suggestions?

**Comment by LaurenzV** [comment]
I have a question, do you think it would be possible to add a way so that when calculating the bounding boxes, filter regions are taken into consideration as well?

My use case is that I want to use resvg to render groups that have filters into an image and then include them in the PDF (so that we can have support for filters in `svg2pdf` as well, which hasn't been implemented yet because PDF doesn't have native support for those. So rasterizing is the only option). But in order to do that, for each group I need to know what it's bounding box is, taking into consideration any possible filters (i.e. their filter regions). Any ideas? Or am I best off just copy ing the current code and adapt it so that filters are considered as well?

**Comment by RazrFalcon** [comment]
@LaurenzV This actually would be added soon. I plan to drop the `resvg::Tree` completely and it does have such bboxes.

And there are long terms plan to do filters flattening on the usvg side, but I still have no idea how. Because this way usvg should depend on resvg and not the other way around.

**Comment by LaurenzV** [comment]
Oh that's awesome, looking forward to it!

**Comment by RazrFalcon** [comment]
@LaurenzV added `usvg::Node::filters_bounding_box`

**Comment by LaurenzV** [comment]
I'm trying to port over to the new usvg version! The new API seems to work very nicely so far, but regarding `filters_bounding_box`, it seems like it doesn't take into account the children of the group (which is the problem that I mentioned above, because if a subgroup has a filter region that is bigger than the one of the current group, it won't return the correct result. Would it be possible to implement the `filters_bounding_box` in a similar fashion to the normal and stroke one (i.e. recursively), so that I can just call it on a group and then get a bbox that takes the filters of all children into consideration, even if the current group doesn't have any filters?

**Comment by LaurenzV** [comment]
(I'm not sure, maybe this doesn't make sense from the resvg perspective, if so you can just let me know and I'll look into whether I can implement this by myself on my side. The problem when converting a node to PDF, I need to know the bbox of the whole group, taking any filters/strokes/etc. of children into account as well ahead of time, this is why I would need it.)

**Comment by RazrFalcon** [comment]
Yep, I've stumbled on it too. The current code is correct, but should be used for different stuff. I will add `layer_bbox` soon.

**Comment by RazrFalcon** [comment]
@LaurenzV Another huge rewrite. Checkout `usvg::Group::layer_bounding_box`. Remember that it's in object units, not canvas one.
I'm not sure this is exactly what you want, but this is what `resvg` uses during rendering.

**Comment by LaurenzV** [comment]
Will try it! Just a small thing I noticed, is it intended that this one uses `NonZeroRect` instead of `Rect` like the others?

**Comment by LaurenzV** [comment]
Yess, it's exactly what I needed and it seems to work nicely, thank you!!

**Comment by RazrFalcon** [comment]
Oops, missed your last message. 

The use of `NonZeroRect` is intentional. `layer_bounding_box` is basically a pixel size of a pixmap a renderer should allocate, therefore it cannot have zero width or height. 
I plan to switch `stroke_bounding_box` to `NonZeroRect` as well, because stroke cannot have zero width or height either.

`object_bounding_box`, on the other hand, is special and can have zero width and/or height. This is perfectly normal.
For example, a horizontal line has no height. And a path like `M 0 0 L 0 0` is perfectly valid as well.

**Comment by yisibl** [comment]
@RazrFalcon There seems to be a bit of a problem with stroke_bounding_box, there is extra white space between the yellow border and the green heart on the left and bottom side, expecting it to be right next to each other.

![image](https://github.com/RazrFalcon/resvg/assets/2784308/ca3188f9-0c3c-42e1-bd29-9546e34b4af5)


```html
<svg viewBox="-40 0 180 260" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g>
    <g fill="green" transform="rotate(-10 50 100) translate(-36 45.5) skewX(40) scale(1 0.5)">
      <path id="heart" d="M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z" />
    </g>
    <use xlink:href="#heart" fill="none" stroke="red" stroke-width="10" />
  </g>
</svg>
```

**Comment by RazrFalcon** [comment]
Ugh... yeah, skew and rotate transforms aren't handled correctly. Will see how it can be fixed without recalculating the whole path.
Getting the node bbox in canvas coordinates is one of the hardest things in SVG.

At least it doesn't affect rendering, since the bbox is always too big.

**Comment by yisibl** [comment]
> Ugh... yeah, skew and rotate transforms aren't handled correctly. Will see how it can be fixed without recalculating the whole path. Getting the node bbox in canvas coordinates is one of the hardest things in SVG.
> 
> At least it doesn't affect rendering, since the bbox is always too big.

In the current `resvg-js` we backported the [`bbox_with_transform`](https://github.com/zimond/resvg/commit/3495d8705b302d6d266748516973606ca9657906#diff-f54c7db7f50224ef024dbcc84918e5d109037be46cbab7656e76535c1e67dba1R1336) method, can we re-add it in a later version of resvg?

**Comment by RazrFalcon** [comment]
The old `bbox_with_transform` is even more broken. I will fix the new implementation soon.

**Comment by RazrFalcon** [comment]
@yisibl please try the latest git version. Should be fixed for paths. Text with skew/rotate is still broken, but it would a bit harder/expensive to fix.
