### ISSUE TITLE
base-line shift `super` and `sub` not working?

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg#673]
According to the resvg-test-suite, both, Chrome and resvg render the following test case correctly:
```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"
     font-family="Noto Sans" font-size="26">
  <title>Deeply nested `super`</title>

  <path id="crosshair" d="M 20 100 L 180 100 M 100 20 L 100 180"
        stroke="gray" stroke-width="0.5"/>

  <text id="text1" x="30" y="100">
    A
    <tspan id="tspan1" fill="green" baseline-shift="super">
      B
      <tspan id="tspan2" fill="green" baseline-shift="super">
        C
        <tspan id="tspan3" fill="green" baseline-shift="super">
          D
          <tspan id="tspan4" fill="green" baseline-shift="super">
            E
            <tspan id="tspan5" fill="green" baseline-shift="super">
              F
            </tspan>
          </tspan>
        </tspan>
      </tspan>
    </tspan>
  </text>

  <!-- image frame -->
  <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

However, in Chrome I get this result:
<img width="963" alt="image" src="https://github.com/RazrFalcon/resvg/assets/47084093/c206e4f0-b1be-4b4a-a3bf-7f4c3515120f">
While in resvg, the result looks like this (ignore the dark background color):
<img width="825" alt="image" src="https://github.com/RazrFalcon/resvg/assets/47084093/3520cab3-11c5-4d70-a1a4-b7ca82e099e5">

I believe the one from Chrome is correct? In addition to that, I also get a warning `Warning (in usvg_parser::svgtree:282): Failed to parse baseline-shift value: 'super'.`

**Comment by RazrFalcon** [comment]
>I believe the one from Chrome is correct?

No. Both are correct. The vertical offset used by sub/super is undefined and a renderer can use whatever we want.
resvg uses font metrics, while some apps simply hardcode those values.

Remember that SVG text is a joke and it's not possible to get reproducible output by design. You have to use PDF for this. Or simply convert text to paths.

>Warning (in usvg_parser::svgtree:282): Failed to parse baseline-shift value: 'super'.

Meh... this is just a spurious warning. We're trying to parse `baseline-shift` as a number first and then as a string. Therefore any non-number value produces a pointless warning... Created #676

**Comment by LaurenzV** [comment]
Okay, good to know. Thanks!
