### ISSUE TITLE
How do I use resvg and usvg as standalone applications?

### ISSUE THREAD

**Issue by samueln-w** [RazrFalcon/resvg#819]
This looks like a very useful project, and your README goes into immense detail on exactly why I should be interested in using it.  But I've never used Rust, so I'm only really interested in the CLI application the README mentions.  But I don't see an explanation of where to find this CLI application, or how to build it, or how to use it.  Could you please help me understand how I can use this project as a standalone CLI application?  I'm interested in both the `resvg` binary (e.g. to convert an SVG file to a raster image like a PNG) and the `usvg` binary (e.g. to convert SVG to Micro SVG, which seems like a useful format).

**Comment by RazrFalcon** [comment]
You can find prebuilt binaries in releases: https://github.com/RazrFalcon/resvg/releases

As for building from scratch, it's the same as for every Rust project. That's why I'm not mentioning this.
Basically, [install Rust](https://www.rust-lang.org/tools/install) and then run `cargo build --release` in `crates/resvg` or `crates/usvg` and then you will find binaries in `target/release`.

**Comment by samueln-w** [comment]
Okay, I think I understand.  Thank you very much!
