### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by sorairolake** [RazrFalcon/resvg#826]
Benchmark tests available in nightly Rust, and this can be run as follows:

```sh
cargo +nightly bench
```

If it's acceptable to add this, I'll write it for `resvg` and `usvg`.

- <https://doc.rust-lang.org/unstable-book/library-features/test.html>

**Comment by RazrFalcon** [comment]
You can use [bencher](https://crates.io/crates/bencher) on stable just fine.

As for the benchmarks, the main reason we don't have them is that they would be sort of pointless. We cannot easily compare `resvg` performance with other libraries and measuring `resvg` performance on its own doesn't really make much sense, since we're not changing anything, so regressions are unlikely.

What is your goal with benchmarks? And what exactly are you plan to benchmark?

**Comment by sorairolake** [comment]
> What is your goal with benchmarks? And what exactly are you plan to benchmark?

Because I thought it would be useful to be able to measure the performance of `resvg` and `usvg`.

But if this doesn't make much sense, this addition may not be necessary.

**Comment by RazrFalcon** [comment]
Sorry, but no. Not very useful.
